apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: color-manager-app
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://shopsphere_db_user:12345678900African@shopsphere-prod.ktkkmbc.mongodb.net/github-action-eks
